### ISSUE TITLE
Analyze expenses

### ISSUE THREAD

**Issue by cminguelazamarro** [jvinoss/GESPRO_Practica_2_Curso_2024_2025#12]

**Comment by jvinoss** [comment]
¿Es posible analizar mis gastos utilizando esta aplicación?

**Comment by cminguelazamarro** [comment]
> ¿Es posible analizar mis gastos utilizando esta aplicación?

Si, a través de esta aplicación puedes analizar los gastos y obtener detalles del banco sin ningún problema
